import { useState, useEffect, useRef } from "react";

/* ═══════════════════════════════════════════════════════════
   EMOTION OS APP v1.2 — Phase 1 Complete
   Haru-Tech Lab / 4-Tab Architecture
   Home · Scan · Action · Library + Couple Bridge
   ═══════════════════════════════════════════════════════════ */

const FF=`'Pretendard',-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif`;

// ─── TUNED QUESTIONS v1.2 ───────────────────────────────
const QS=[
  {id:"I01",p:"최근 2주간, 쉬고 있을 때조차 다음에 해야 할 일이 자동으로 떠올라 머리가 쉬지 못했다.",pq:"Q1",sq:"Q6",r1:"R2",leak:"조절단",bug:"MND-OVERCLOCK-01",bugL:"과속 실행 버그",patch:"Slow-Down Patch",patchL:"속도 강제 저하 패치",mode:"슬로모드",modeD:"속도를 낮추고 긴장을 풀어 조절단 과열을 식히는 운영 자세"},
  {id:"I02",p:"최근 2주간, 빨리 끝내려다 실수하거나 중요한 단계를 건너뛴 적이 있었다.",pq:"Q1",sq:"Q4",r1:"R2",leak:"조절단",bug:"MND-OVERCLOCK-01",bugL:"과속 실행 버그",patch:"Slow-Down Patch",patchL:"속도 강제 저하 패치",mode:"슬로모드",modeD:"속도를 낮추고 긴장을 풀어 조절단 과열을 식히는 운영 자세"},
  {id:"I03",p:"최근 2주간, 진행이 느려지거나 멈추면 몸이 먼저 긴장되고 불안감이 올라왔다.",pq:"Q1",sq:"Q4",r1:"R2",leak:"조절단",bug:"MND-OVERCLOCK-01",bugL:"과속 실행 버그",patch:"Slow-Down Patch",patchL:"속도 강제 저하 패치",mode:"슬로모드",modeD:"속도를 낮추고 긴장을 풀어 조절단 과열을 식히는 운영 자세"},
  {id:"I04",p:"최근 2주간, 상대의 사소한 말투나 미세한 표정 변화에 신경이 날카롭게 반응했다.",pq:"Q2",sq:"Q4",r1:"R1",leak:"입력단",bug:"MND-INPUTFLOOD-01",bugL:"자극 과부하 버그",patch:"Sensory Reset",patchL:"감각 리셋 루틴",mode:"무심 모드",modeD:"외부 자극과 해석 과부하를 줄여 입력단 부담을 낮추는 운영 자세"},
  {id:"I05",p:"최근 2주간, 사람이 많거나 소음이 큰 공간에 있으면 평소보다 빠르게 에너지가 빠졌다.",pq:"Q2",sq:"Q5",r1:"R1",leak:"입력단",bug:"MND-INPUTFLOOD-01",bugL:"자극 과부하 버그",patch:"Sensory Reset",patchL:"감각 리셋 루틴",mode:"무심 모드",modeD:"외부 자극과 해석 과부하를 줄여 입력단 부담을 낮추는 운영 자세"},
  {id:"I06",p:"최근 2주간, 특별히 힘든 일이 없었는데도 하루가 끝나면 감각이 과부하된 느낌이 들었다.",pq:"Q2",sq:"Q3",r1:"R1",leak:"입력단",bug:"MND-INPUTFLOOD-01",bugL:"자극 과부하 버그",patch:"Sensory Reset",patchL:"감각 리셋 루틴",mode:"무심 모드",modeD:"외부 자극과 해석 과부하를 줄여 입력단 부담을 낮추는 운영 자세"},
  {id:"I07",p:"최근 2주간, 마음이 불편한데 그게 정확히 어떤 감정인지 이름을 붙이기 어려운 순간이 많았다.",pq:"Q3",sq:"Q2",r1:"R1",leak:"처리단",bug:"MND-EMOSUPPRESS-01",bugL:"감정 억압 버그",patch:"Voice Activation",patchL:"표현 활성화 패치",mode:"감정읽기 모드",modeD:"회피된 감정을 이름 붙여 처리단 정체를 풀어 주는 운영 자세"},
  {id:"I08",p:"최근 2주간, 속으로는 서운하거나 화가 났지만 겉으로는 아무렇지 않은 듯 넘긴 적이 많았다.",pq:"Q3",sq:"Q7",r1:"R1",leak:"처리단",bug:"MND-EMOSUPPRESS-01",bugL:"감정 억압 버그",patch:"Voice Activation",patchL:"표현 활성화 패치",mode:"감정읽기 모드",modeD:"회피된 감정을 이름 붙여 처리단 정체를 풀어 주는 운영 자세"},
  {id:"I09",p:"최근 2주간, 이미 끝난 일인데도 설명하기 어려운 무거움이 마음에 계속 남아 있었다.",pq:"Q3",sq:"Q5",r1:"R1",leak:"처리단",bug:"MND-EMOSUPPRESS-01",bugL:"감정 억압 버그",patch:"Voice Activation",patchL:"표현 활성화 패치",mode:"감정읽기 모드",modeD:"회피된 감정을 이름 붙여 처리단 정체를 풀어 주는 운영 자세"},
  {id:"I10",p:"최근 2주간, 감정을 누르고 있다가 어느 순간 예상보다 크게 한꺼번에 터져나온 적이 있었다.",pq:"Q4",sq:"Q1",r1:"R3",leak:"출력단",bug:"MND-OUTPUTHEAT-01",bugL:"출력 과열 버그",patch:"Stop Signal",patchL:"출력 차단 신호 패치",mode:"평정 모드",modeD:"폭발 직전의 출력단을 진정시키고 반응 속도를 늦추는 운영 자세"},
  {id:"I11",p:"최근 2주간, 흥분하거나 화가 나면 말이 빨라지고 세져서 끝나고 나서 후회한 적이 있었다.",pq:"Q4",sq:"Q1",r1:"R3",leak:"출력단",bug:"MND-OUTPUTHEAT-01",bugL:"출력 과열 버그",patch:"Stop Signal",patchL:"출력 차단 신호 패치",mode:"평정 모드",modeD:"폭발 직전의 출력단을 진정시키고 반응 속도를 늦추는 운영 자세"},
  {id:"I12",p:"최근 2주간, 감정을 표현하고 나면 해소되기보다 오히려 더 깊은 피로나 수치심이 남았다.",pq:"Q4",sq:"Q6",r1:"R3",leak:"출력단",bug:"MND-OUTPUTHEAT-01",bugL:"출력 과열 버그",patch:"Stop Signal",patchL:"출력 차단 신호 패치",mode:"평정 모드",modeD:"폭발 직전의 출력단을 진정시키고 반응 속도를 늦추는 운영 자세"},
  {id:"I13",p:"최근 2주간, 해야 할 일이 눈앞에 있는데도 몸에 시동이 걸리지 않는 느낌이 반복됐다.",pq:"Q5",sq:"Q3",r1:"R4",leak:"회복단",bug:"BDY-BOOTFAIL-01",bugL:"시동 실패 버그",patch:"Baseline Reset",patchL:"기준선 복구 패치",mode:"무빙 모드",modeD:"최소 움직임으로 정지된 시스템의 재가동을 돕는 운영 자세"},
  {id:"I14",p:"최근 2주간, 많이 하지 않았는데도 하루 끝에 바닥까지 방전된 것 같은 피로가 있었다.",pq:"Q5",sq:"Q2",r1:"R4",leak:"회복단",bug:"BDY-LOWPOWERLOCK-01",bugL:"저출력 고착 버그",patch:"Baseline Reset",patchL:"기준선 복구 패치",mode:"무빙 모드",modeD:"최소 움직임으로 정지된 시스템의 재가동을 돕는 운영 자세"},
  {id:"I15",p:"최근 2주간, 누워 있는 시간이 길어질수록 오히려 더 움직이기 힘들어지는 악순환이 있었다.",pq:"Q5",sq:"Q6",r1:"R4",leak:"회복단",bug:"BDY-BEDLOCK-01",bugL:"침대 고착 버그",patch:"Baseline Reset",patchL:"기준선 복구 패치",mode:"무빙 모드",modeD:"최소 움직임으로 정지된 시스템의 재가동을 돕는 운영 자세"},
  {id:"I16",p:"최근 2주간, 다른 사람과 비교한 뒤 자신이 초라하고 뒤처졌다는 느낌이 오래 지속됐다.",pq:"Q6",sq:"Q5",r1:"R1",leak:"처리단",bug:"MND-SELFDEVALUE-01",bugL:"자기비하 증폭 버그",patch:"Permission Reset",patchL:"허용 기준 복구 패치",mode:"최선 모드",modeD:"타인 기준이 아닌 과정 기준으로 비교 오염을 줄이는 운영 자세"},
  {id:"I17",p:"최근 2주간, 누군가의 성취를 접한 직후 내가 세워둔 기준이 갑자기 흔들리는 느낌이 있었다.",pq:"Q6",sq:"Q1",r1:"R1",leak:"처리단",bug:"MND-FALSEPATCH-01",bugL:"가짜 패치 버그",patch:"Benchmark Filter",patchL:"기준 필터 패치",mode:"최선 모드",modeD:"타인 기준이 아닌 과정 기준으로 비교 오염을 줄이는 운영 자세"},
  {id:"I18",p:"최근 2주간, SNS나 메신저에서 타인의 근황을 확인한 뒤 자신의 상태를 다시 점검하거나 비교한 적이 잦았다.",pq:"Q6",sq:"Q7",r1:"R1",leak:"처리단",bug:"MND-SELFDEVALUE-01",bugL:"자기비하 증폭 버그",patch:"Permission Reset",patchL:"허용 기준 복구 패치",mode:"최선 모드",modeD:"타인 기준이 아닌 과정 기준으로 비교 오염을 줄이는 운영 자세"},
  {id:"I19",p:"최근 2주간, 일이 예상대로 정리되지 않으면 몸 전체가 경직되고 마음이 과하게 조여왔다.",pq:"Q7",sq:"Q3",r1:"R2",leak:"조절단",bug:"MND-OVERCONTROL-01",bugL:"과통제 버그",patch:"Root Reset",patchL:"근원 재설정 패치",mode:"설렁설렁 모드",modeD:"과도한 통제와 완벽주의를 낮춰 조절단 경직을 푸는 운영 자세"},
  {id:"I20",p:"최근 2주간, 작은 실수나 사소한 허술함을 쉽게 흘려보내지 못하고 계속 붙들었다.",pq:"Q7",sq:"Q4",r1:"R2",leak:"조절단",bug:"MND-OVERCONTROL-01",bugL:"과통제 버그",patch:"Root Reset",patchL:"근원 재설정 패치",mode:"설렁설렁 모드",modeD:"과도한 통제와 완벽주의를 낮춰 조절단 경직을 푸는 운영 자세"},
  {id:"I21",p:"최근 2주간, 쉬는 시간에도 무언가를 정리하거나 통제하려는 상태에서 완전히 벗어나지 못했다.",pq:"Q7",sq:"Q5",r1:"R2",leak:"조절단",bug:"MND-OVERCONTROL-01",bugL:"과통제 버그",patch:"Root Reset",patchL:"근원 재설정 패치",mode:"설렁설렁 모드",modeD:"과도한 통제와 완벽주의를 낮춰 조절단 경직을 푸는 운영 자세"},
];

const QL={Q1:"Q1 조급형",Q2:"Q2 과민형",Q3:"Q3 회피형",Q4:"Q4 분출형",Q5:"Q5 우울형",Q6:"Q6 비교형",Q7:"Q7 통제형"};
const QSH={Q1:"조급",Q2:"과민",Q3:"회피",Q4:"분출",Q5:"우울",Q6:"비교",Q7:"통제"};
const RL={R1:"R1 인지",R2:"R2 조절",R3:"R3 공명",R4:"R4 회복",R5:"R5 갱신"};
const RD={R1:"감정을 읽고 구분하는 기능에 부담이 높습니다.",R2:"속도, 경계, 긴장을 조절하는 기능에 부담이 높습니다.",R3:"관계 안에서 감정을 조율하고 반응하는 기능에 부담이 높습니다.",R4:"가용성을 복구하고 다시 살아나는 기능에 부담이 높습니다.",R5:"반복 패턴을 수정하고 기준을 세우는 기능에 부담이 높습니다."};
const LD={"입력단":"외부 자극이 과도하게 들어와 시스템이 쉽게 과부하되는 구간입니다.","처리단":"감정을 해석하고 의미를 붙이는 과정에서 정체나 왜곡이 생기는 구간입니다.","조절단":"속도, 긴장, 통제 조절이 어려워 과열되기 쉬운 구간입니다.","출력단":"감정이 말이나 행동으로 전환될 때 폭주하거나 손실이 생기는 구간입니다.","회복단":"에너지 복구와 가동성 재확보가 잘 이루어지지 않는 구간입니다.","갱신단":"반복 패턴을 업데이트하지 못해 같은 오류가 재생되는 구간입니다."};
const SCALE=[{v:0,l:"전혀 아니다"},{v:1,l:"가끔 그렇다"},{v:2,l:"자주 그렇다"},{v:3,l:"거의 항상 그렇다"}];

// ─── HOTFIX DB ──────────────────────────────────────────
const HOTFIX_DB=[
  {ref:"universal-reset",label:"3분 리셋",desc:"모든 것을 멈추고 3분간 아무것도 하지 않습니다. 눈을 감고 호흡만 느끼세요.",cta:"지금 리셋하기",priority:0,bandMatch:["overload","low"],qMatch:null},
  {ref:"slow-down",label:"속도 낮추기",desc:"지금 하고 있는 모든 일의 속도를 의식적으로 절반으로 줄입니다.",cta:"속도 낮추기",priority:1,bandMatch:null,qMatch:["Q1","Q7"]},
  {ref:"sensory-reset",label:"자극 차단",desc:"소리, 빛, 알림 등 외부 입력을 5분간 최소화합니다.",cta:"자극 차단하기",priority:1,bandMatch:null,qMatch:["Q2"]},
  {ref:"stop-signal",label:"출력 멈춤",desc:"말하거나 반응하려는 충동을 10초간 멈추고 내부를 먼저 점검합니다.",cta:"일단 멈추기",priority:1,bandMatch:null,qMatch:["Q4"]},
  {ref:"baseline-reset",label:"기준선 복구",desc:"가장 작은 움직임 하나(물 한 잔, 창문 열기)로 시스템 재가동을 시도합니다.",cta:"회복 시작하기",priority:1,bandMatch:null,qMatch:["Q5"]},
  {ref:"voice-activate",label:"감정 이름 붙이기",desc:"지금 느끼는 것에 한 단어로 이름을 붙여봅니다. 정확하지 않아도 됩니다.",cta:"감정 읽기",priority:2,bandMatch:null,qMatch:["Q3"]},
  {ref:"permission-reset",label:"허용 기준 복구",desc:"'지금까지 한 것'을 하나 떠올리고 그것으로 충분하다고 허락합니다.",cta:"기준 복구하기",priority:2,bandMatch:null,qMatch:["Q6"]},
];

// ─── PROTOCOL DB (7 items, one per Q) ───────────────────
const PROTO_DB=[
  {ref:"slow-proto",label:"슬로모드 프로토콜",desc:"말의 속도를 늦추고, 결론을 서두르지 않고, 한 번에 하나만 처리합니다.",qMatch:["Q1"]},
  {ref:"sensory-proto",label:"감각 보호 프로토콜",desc:"자극이 많은 환경에서 의식적으로 입력량을 줄이는 운영 가이드입니다.",qMatch:["Q2"]},
  {ref:"naming-proto",label:"감정읽기 프로토콜",desc:"하루에 한 번, 지금 느끼는 감정에 이름을 붙이는 연습입니다.",qMatch:["Q3"]},
  {ref:"output-proto",label:"출력 제어 프로토콜",desc:"감정이 올라올 때 '10초 멈춤 → 한 문장 정리 → 전달'의 3단계를 따릅니다.",qMatch:["Q4"]},
  {ref:"coldstart-proto",label:"콜드 스타트 프로토콜",desc:"시동이 안 걸릴 때 '가장 작은 움직임 하나'부터 시작합니다.",qMatch:["Q5"]},
  {ref:"benchmark-proto",label:"기준 필터 프로토콜",desc:"비교 충동이 올 때 '어제보다 나아진 점 하나'를 떠올립니다.",qMatch:["Q6"]},
  {ref:"drop-proto",label:"통제 내려놓기 프로토콜",desc:"완벽하게 정리하려는 충동이 올 때, 의도적으로 80%에서 멈춥니다.",qMatch:["Q7"]},
];

// ─── PRACTICE DB (9 items, Q-matched) ───────────────────
const PRAC_DB=[
  {ref:"slow-breath",label:"3분 감속 호흡",desc:"들숨 4초, 날숨 6초로 호흡 속도를 의식적으로 늦추는 연습입니다.",qMatch:["Q1","Q7"]},
  {ref:"stim-log",label:"자극 일지 기록",desc:"오늘 가장 많은 에너지를 뺏은 자극 3개를 적어봅니다.",qMatch:["Q2"]},
  {ref:"emo-name",label:"감정 이름 붙이기",desc:"지금 느끼는 것에 3초 안에 한 단어로 이름을 붙이는 훈련입니다.",qMatch:["Q3"]},
  {ref:"10sec-pause",label:"10초 멈춤 연습",desc:"감정이 올라올 때 반응 전에 속으로 10을 세는 연습입니다.",qMatch:["Q4"]},
  {ref:"micro-move",label:"1분 마이크로 무빙",desc:"발만 바닥에 대기, 팔 한번 들기 같은 최소 움직임으로 재가동을 연습합니다.",qMatch:["Q5"]},
  {ref:"process-chk",label:"과정 체크 연습",desc:"오늘 '결과'가 아닌 '과정'에서 잘한 점 하나를 떠올리는 연습입니다.",qMatch:["Q6"]},
  {ref:"80pct-rule",label:"80% 허용 연습",desc:"오늘 하나의 일을 의도적으로 80%에서 멈추는 연습입니다.",qMatch:["Q7"]},
  {ref:"trigger-sig",label:"Trigger Signal 연습",desc:"손바닥(Stop), 손가락 2개(Time-out), [프리즈] 키워드를 미리 연습합니다.",qMatch:["Q3","Q4"]},
  {ref:"safe-exit",label:"Safe Exit 문장 연습",desc:"\"20분간 연결을 끊지만 반드시 다시 연결합니다\" 문장을 미리 연습합니다.",qMatch:["Q3","Q4"]},
];

// ─── LIBRARY (16 items) ─────────────────────────────────
const LIB=[
  {cat:"핵심 프레임",title:"Emotion OS",desc:"감정을 운영체제로 읽는 상위 프레임",url:"https://www.notion.so/Emotion-OS-324604b060a4805abeb8cd69aca313c9"},
  {cat:"핵심 프레임",title:"5R 기본 구조",desc:"인지 → 조절 → 공명 → 회복 → 갱신",url:"https://www.notion.so/5R-v1-3-320604b060a480f9bbbcd74d09be6ec8"},
  {cat:"핵심 프레임",title:"감정공학이란 무엇인가",desc:"감정공학의 정의와 목적",url:"https://www.notion.so/v1-3-31f604b060a480a88245fb446ea1bb1a"},
  {cat:"핵심 프레임",title:"호모 레귤란스",desc:"Emotion OS를 일상적으로 가동하는 인간형",url:"https://www.notion.so/Homo-Regulans-v2-5-321604b060a4809ab446f745c72b7e68"},
  {cat:"진단 체계",title:"감정누수 유형 총론",desc:"7가지 감정 누수 패턴 분류",url:"https://www.notion.so/Q1-Q7-v1-3-325604b060a480b18e42f438fa5b7e43"},
  {cat:"진단 체계",title:"Bug란 무엇인가",desc:"반복되는 운영 오류의 표준 단위",url:"https://www.notion.so/Bug-329604b060a4806e9af4e2720535a00e"},
  {cat:"진단 체계",title:"Patch란 무엇인가",desc:"Bug에 개입하는 수정 조치",url:"https://www.notion.so/Patch-329604b060a480d099a5c020cbe22409"},
  {cat:"OS 영역",title:"Body OS",desc:"몸의 가동성과 회복을 읽는 프레임",url:"https://www.notion.so/Body-OS-329604b060a48005be9cc00ad34b32f7"},
  {cat:"OS 영역",title:"Relation OS",desc:"관계 안의 경계와 공명을 읽는 프레임",url:"https://www.notion.so/Relation-OS-329604b060a480dabedce49cd532b625"},
  {cat:"심화 주제",title:"회복과 감각 리셋의 원리",desc:"R4 회복의 구조와 실전 적용",url:"https://www.notion.so/R4-v1-3-326604b060a480829a7eef09c9f885df"},
  {cat:"심화 주제",title:"감정 경계의 필요성",desc:"R2 조절과 경계 설정의 원리",url:"https://www.notion.so/R2-v1-3-326604b060a4801bb755fa9585666a26"},
  {cat:"심화 주제",title:"감정억제와 왜곡분출",desc:"억압과 폭발의 구조적 분석",url:"https://www.notion.so/v1-3-320604b060a48025a30cf1ff68024a6d"},
  {cat:"심화 주제",title:"비교 중독과 자기비하",desc:"Q6 비교형의 심층 메커니즘",url:"https://www.notion.so/v1-3-320604b060a48090a854cb5d62a7daf1"},
  {cat:"심화 주제",title:"관계피로와 경계 설정",desc:"관계 안에서 경계가 무너지는 구조",url:"https://www.notion.so/v1-3-320604b060a480d99d1ed16bcf05b560"},
  {cat:"심화 주제",title:"한국형 번아웃의 구조",desc:"한국 사회 특유의 소진 메커니즘",url:"https://www.notion.so/v1-3-320604b060a48047a6fbd5ed8452de6a"},
  {cat:"실전 도구",title:"리커버리 프로토콜",desc:"회복을 위한 구조화된 운영 절차",url:"https://www.notion.so/Recovery-Protocol-v1-4-327604b060a4808f9201d83d9a9c13bb"},
];
const LCATS=["핵심 프레임","진단 체계","OS 영역","심화 주제","실전 도구"];

// ─── NOTION LINKS ───────────────────────────────────────
const NL={bug:"https://www.notion.so/Bug-329604b060a4806e9af4e2720535a00e",patch:"https://www.notion.so/Patch-329604b060a480d099a5c020cbe22409",q:"https://www.notion.so/Q1-Q7-v1-3-325604b060a480b18e42f438fa5b7e43",r5:"https://www.notion.so/5R-v1-3-320604b060a480f9bbbcd74d09be6ec8",rec:"https://www.notion.so/Recovery-Protocol-v1-4-327604b060a4808f9201d83d9a9c13bb"};
const BLinks={"MND-OVERCLOCK-01":"https://www.notion.so/326604b060a48067bd84e0dd1fdf9f07","MND-INPUTFLOOD-01":"https://www.notion.so/326604b060a48019be9bcac800bc768d","MND-EMOSUPPRESS-01":"https://www.notion.so/326604b060a480f0be69e58d38f61451","MND-OUTPUTHEAT-01":"https://www.notion.so/326604b060a480edb48be7ef7259bad4","BDY-BOOTFAIL-01":"https://www.notion.so/326604b060a480e49d80de69bb688bfa","BDY-LOWPOWERLOCK-01":"https://www.notion.so/326604b060a480c1bbedf33b4e3325f1","BDY-BEDLOCK-01":"https://www.notion.so/326604b060a4800f9195e1879f6adaba","MND-SELFDEVALUE-01":"https://www.notion.so/326604b060a4805bb3e4f39fe27642e7","MND-FALSEPATCH-01":"https://www.notion.so/326604b060a4809c9b66f76c9631835a","MND-OVERCONTROL-01":"https://www.notion.so/326604b060a4804da9e9d0927b1af375"};
const PLinks={"Slow-Down Patch":"https://www.notion.so/Slow-Down-Patch-326604b060a480a29a93c43517f3560d","Sensory Reset":"https://www.notion.so/Sensory-Reset-Routine-327604b060a480bd967be841111490f6","Voice Activation":"https://www.notion.so/Voice-Activation-Patch-326604b060a480da82fee6cef256b41e","Stop Signal":"https://www.notion.so/Stop-Signal-Patch-326604b060a48049b883f43b729c4e4b","Baseline Reset":"https://www.notion.so/Baseline-Reset-Patch-327604b060a480a5987ae4ff4cd72deb","Permission Reset":"https://www.notion.so/Permission-Reset-Patch-327604b060a4803c9920e6e431e471e3","Benchmark Filter":"https://www.notion.so/Benchmark-Filter-Patch-326604b060a480e09cd3fb1dd87bea5f","Root Reset":"https://www.notion.so/Root-Reset-Patch-327604b060a480bda42ad01906938209"};

// ─── ENGINE ─────────────────────────────────────────────
function calcFull(a){const s={Q1:0,Q2:0,Q3:0,Q4:0,Q5:0,Q6:0,Q7:0},m={...s};QS.forEach((q,i)=>{const r=a[i]??0;s[q.pq]+=r*0.7;s[q.sq]+=r*0.3;m[q.pq]+=3*0.7;m[q.sq]+=3*0.3;});const n={};Object.keys(s).forEach(k=>n[k]=m[k]>0?Math.round(s[k]/m[k]*1000)/10:0);const st=Object.entries(n).sort((a,b)=>b[1]-a[1]);const pq=st[0][0],sq=st[1][0],hi=st[0][1],mn=Math.round(Object.values(n).reduce((a,b)=>a+b,0)/7*10)/10;let bd="stable";if(hi>=70)bd="overload";else if(hi>=50)bd="low";else if(hi>=30)bd="caution";if(bd==="stable"&&mn>=25)bd="caution";const av=Math.round(100-hi),sp=Object.values(n).filter(v=>v>=30).length>=5,d=QS.find(q=>q.pq===pq);return{nm:n,pq,sq,hi,mean:mn,band:bd,avail:av,spread:sp,leak:d?.leak,r1:d?.r1,bug:d?.bug,bugL:d?.bugL,patch:d?.patch,patchL:d?.patchL,mode:d?.mode,modeD:d?.modeD,ts:Date.now(),type:"full"};}
function getRecheckQs(r){const p=QS.filter(q=>q.pq===r.pq),s=QS.filter(q=>q.pq===r.sq),c=[...p];s.forEach(q=>{if(!c.find(x=>x.id===q.id))c.push(q);});return c.slice(0,5);}
function calcRecheck(a,qs,prev){const s={},m={};Object.keys(prev.nm).forEach(k=>{s[k]=0;m[k]=0;});qs.forEach((q,i)=>{const r=a[i]??0;s[q.pq]+=r*0.7;s[q.sq]+=r*0.3;m[q.pq]+=3*0.7;m[q.sq]+=3*0.3;});const n={...prev.nm};Object.keys(s).forEach(k=>{if(m[k]>0)n[k]=Math.round(s[k]/m[k]*1000)/10;});const st=Object.entries(n).sort((a,b)=>b[1]-a[1]),hi=st[0][1],mn=Math.round(Object.values(n).reduce((a,b)=>a+b,0)/7*10)/10;let bd="stable";if(hi>=70)bd="overload";else if(hi>=50)bd="low";else if(hi>=30)bd="caution";if(bd==="stable"&&mn>=25)bd="caution";const av=Math.round(100-hi);return{nm:n,pq:prev.pq,sq:prev.sq,hi,mean:mn,band:bd,avail:av,spread:Object.values(n).filter(v=>v>=30).length>=5,leak:prev.leak,r1:prev.r1,bug:prev.bug,bugL:prev.bugL,patch:prev.patch,patchL:prev.patchL,mode:prev.mode,modeD:prev.modeD,ts:Date.now(),type:"recheck",delta:av-prev.avail};}
function getHotFixes(r){if(!r)return[];const f=HOTFIX_DB.filter(h=>{if(h.bandMatch&&h.bandMatch.includes(r.band))return true;if(h.qMatch&&(h.qMatch.includes(r.pq)||h.qMatch.includes(r.sq)))return true;return false;}).sort((a,b)=>a.priority-b.priority);if((r.band==="overload"||r.band==="low")&&!f.find(x=>x.ref==="universal-reset"))f.unshift(HOTFIX_DB[0]);return f.slice(0,3);}
function deriveHS(fs,lr){if(!fs&&!lr)return{source:"empty"};const l=lr||fs,s=fs||l;return{source:l.type==="recheck"?"recheck_overlay":"full_scan",avail:l.avail,band:l.band,spread:l.spread,nm:l.nm,pq:s.pq,sq:s.sq,leak:s.leak,r1:s.r1,mode:s.mode,modeD:s.modeD,bug:s.bug,bugL:s.bugL,patch:s.patch,patchL:s.patchL,qpr:l,delta:l.type==="recheck"?l.delta:undefined,isRc:l.type==="recheck",rcNote:l.type==="recheck"&&l.delta!==undefined?(l.delta>0?"회복 중":l.delta<0?"부하 증가":"변화 없음"):null};}

// ─── COLORS & BANDS ─────────────────────────────────────
const C={bg:"#060a14",card:"#0c1120",cardH:"#101828",border:"#182035",borderL:"#243050",text:"#e8ecf4",dim:"#8b95a8",muted:"#5a6478",accent:"#e8654a",accentD:"#e8654a18",teal:"#36c5b0",tealD:"#36c5b012",blue:"#5b8af5",blueD:"#5b8af512",green:"#34d399",amber:"#f5a623",red:"#ef5350",purple:"#a78bfa"};
const BAND={
  stable:{l:"안정",c:C.green,bg:`${C.green}06`,d:"현재 시스템은 비교적 안정적으로 작동하고 있습니다.",sub:"특정 상황에서 누수 패턴이 다시 활성화될 수 있으므로 현재 리듬을 유지하는 것이 좋습니다.",act:"패턴을 미리 이해해두면 다음 과열을 더 빨리 막을 수 있습니다."},
  caution:{l:"주의",c:C.amber,bg:`${C.amber}06`,d:"피로 신호가 감지되기 시작했습니다.",sub:"아직 전면 과부하는 아니지만, 같은 패턴이 반복되면 가동성이 빠르게 떨어질 수 있습니다.",act:"지금 결과를 조기 경고 신호로 활용하는 것이 좋습니다."},
  low:{l:"저하",c:C.accent,bg:`${C.accent}05`,d:"시스템 가동성이 눈에 띄게 떨어진 상태입니다.",sub:"회복보다 버티기가 앞서고 있을 가능성이 높습니다.",act:"지금은 해석보다 부하 완화와 회복 확보가 우선입니다."},
  overload:{l:"과부하",c:C.red,bg:`${C.red}05`,d:"시스템이 과열 또는 저전력 상태에 가깝습니다.",sub:"좋은 조언도 잘 들어오지 않을 수 있습니다.",act:"문제 해결보다 먼저 가동성 회복이 필요합니다."},
};

// ─── UI PRIMITIVES ──────────────────────────────────────
function useCountUp(t,dur=1000){const[v,setV]=useState(0);const r=useRef(null);useEffect(()=>{const s=performance.now();const step=n=>{const p=Math.min((n-s)/dur,1);setV(Math.round(t*(1-Math.pow(1-p,3))));if(p<1)r.current=requestAnimationFrame(step);};r.current=requestAnimationFrame(step);return()=>{if(r.current)cancelAnimationFrame(r.current);};},[t,dur]);return v;}
const ANum=({value,color,size=24,suffix=""})=>{const d=useCountUp(value);return (<span style={{fontSize:size,fontWeight:800,color,fontFamily:FF}}>{d}{suffix}</span>);};
const DBadge=({delta,big})=>{if(delta==null)return null;const up=delta>=0,z=delta===0,co=z?C.dim:up?C.green:C.red,ar=z?"→":up?"↑":"↓";return(<div style={{display:"inline-flex",alignItems:"center",gap:big?8:5,padding:big?"8px 16px":"4px 12px",borderRadius:big?12:16,background:`${co}12`,border:`1px solid ${co}25`,animation:z?undefined:"dF 0.6s ease"}}><span style={{fontSize:big?20:14,fontWeight:800,color:co}}>{ar}</span><span style={{fontSize:big?16:12,fontWeight:700,color:co,fontFamily:FF}}>{up&&!z?"+":""}{delta}%</span>{!z&&<span style={{fontSize:big?11:9,color:`${co}aa`}}>{up?"회복 중":"주의 필요"}</span>}</div>);};
const Card=({children,accent,style:s,onClick})=>(<div onClick={onClick} style={{background:C.card,border:`1px solid ${accent||C.border}`,borderRadius:14,padding:"20px 18px",marginBottom:14,cursor:onClick?"pointer":"default",...s}}>{children}</div>);
const Badge=({text,color})=>(<span style={{display:"inline-block",padding:"3px 10px",borderRadius:16,fontSize:10,fontWeight:700,color,background:`${color}15`,border:`1px solid ${color}25`,fontFamily:FF}}>{text}</span>);
const MiniBar=({pct,color,h=5})=>(<div style={{width:"100%",height:h,background:C.border,borderRadius:h/2,overflow:"hidden"}}><div style={{width:`${Math.max(pct,2)}%`,height:"100%",background:color,borderRadius:h/2,transition:"width 1s ease"}}/></div>);
const Btn=({children,onClick,primary,small,style:s,disabled})=>(<button disabled={disabled} onClick={onClick} style={{padding:small?"10px 18px":"14px 24px",borderRadius:12,border:primary?"none":`1px solid ${C.border}`,background:primary?`linear-gradient(135deg,${C.accent},#d4523a)`:"transparent",color:primary?"#fff":C.dim,fontSize:small?13:14,fontWeight:600,fontFamily:FF,cursor:disabled?"default":"pointer",opacity:disabled?0.4:1,width:"100%",...s}}>{children}</button>);
function Accordion({title,children,defaultOpen=false}){const[o,setO]=useState(defaultOpen);return(<Card><button onClick={()=>setO(!o)} style={{display:"flex",justifyContent:"space-between",alignItems:"center",width:"100%",background:"none",border:"none",padding:0,cursor:"pointer",fontFamily:FF}}><span style={{fontSize:12,color:C.muted}}>{title}</span><span style={{fontSize:14,color:C.muted,transform:o?"rotate(180deg)":"rotate(0)",transition:"transform 0.3s"}}>▾</span></button>{o&&<div style={{marginTop:10}}>{children}</div>}</Card>);}

// ─── ICONS & NAV ────────────────────────────────────────
const IH=({a})=>(<svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke={a?C.accent:C.muted} strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 9l9-7 9 7v11a2 2 0 01-2 2H5a2 2 0 01-2-2z"/><polyline points="9 22 9 12 15 12 15 22"/></svg>);
const IS=({a})=>(<svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke={a?C.accent:C.muted} strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="11" cy="11" r="8"/><line x1="21" y1="21" x2="16.65" y2="16.65"/></svg>);
const IA=({a})=>(<svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke={a?C.accent:C.muted} strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2"/></svg>);
const IL=({a})=>(<svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke={a?C.accent:C.muted} strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 19.5A2.5 2.5 0 016.5 17H20"/><path d="M6.5 2H20v20H6.5A2.5 2.5 0 014 19.5v-15A2.5 2.5 0 016.5 2z"/></svg>);
function BNav({tab,setTab}){const ts=[{id:"home",I:IH,l:"Home"},{id:"scan",I:IS,l:"Scan"},{id:"action",I:IA,l:"Action"},{id:"library",I:IL,l:"Library"}];return(<div style={{position:"fixed",bottom:0,left:0,right:0,background:C.bg,borderTop:`1px solid ${C.border}`,display:"flex",justifyContent:"space-around",padding:"8px 0 env(safe-area-inset-bottom,8px)",zIndex:200}}>{ts.map(t=>{const a=tab===t.id;return(<button key={t.id} onClick={()=>setTab(t.id)} style={{background:"none",border:"none",display:"flex",flexDirection:"column",alignItems:"center",gap:3,cursor:"pointer",padding:"4px 12px",opacity:a?1:0.55}}><t.I a={a}/><span style={{fontSize:10,fontWeight:a?700:500,color:a?C.accent:C.muted,fontFamily:FF}}>{t.l}</span></button>);})}</div>);}

// ─── 5R RADAR ───────────────────────────────────────────
const RK=["R1","R2","R3","R4","R5"],RS={R1:"인지",R2:"조절",R3:"공명",R4:"회복",R5:"갱신"};
function R5Radar({pr,result}){const rL={R1:0,R2:0,R3:0,R4:0,R5:0};QS.forEach(q=>{if(q.r1)rL[q.r1]=Math.max(rL[q.r1],result.nm[q.pq]||0);});const cx=75,cy=75,rd=55,as=2*Math.PI/5,sa=-Math.PI/2;const pts=RK.map((k,i)=>{const a=sa+i*as,r=rd*Math.max(Math.min(rL[k]/100,1),0.08);return{x:cx+r*Math.cos(a),y:cy+r*Math.sin(a),k};});const lps=RK.map((k,i)=>{const a=sa+i*as,r=rd+16;return{x:cx+r*Math.cos(a),y:cy+r*Math.sin(a),k};});return(<div style={{display:"flex",justifyContent:"center",margin:"12px 0 8px"}}><svg width={150} height={150} viewBox="0 0 150 150">{[.33,.66,1].map(s=>(<polygon key={s} points={RK.map((k,i)=>{const a=sa+i*as,r=rd*s;return`${cx+r*Math.cos(a)},${cy+r*Math.sin(a)}`;}).join(" ")} fill="none" stroke={C.border} strokeWidth=".5"/>))}{RK.map((k,i)=><line key={i} x1={cx} y1={cy} x2={cx+rd*Math.cos(sa+i*as)} y2={cy+rd*Math.sin(sa+i*as)} stroke={C.border} strokeWidth=".5"/>)}<polygon points={pts.map(p=>`${p.x},${p.y}`).join(" ")} fill={`${C.accent}20`} stroke={C.accent} strokeWidth="1.5"/>{pts.map((p,i)=><circle key={i} cx={p.x} cy={p.y} r={p.k===pr?4:2.5} fill={p.k===pr?C.accent:C.dim}/>)}{lps.map((p,i)=>(<text key={i} x={p.x} y={p.y} textAnchor="middle" dominantBaseline="middle" style={{fontSize:9,fontWeight:p.k===pr?800:500,fill:p.k===pr?C.accent:C.dim,fontFamily:FF}}>{RS[p.k]}</text>))}</svg></div>);}

// ─── HOME ───────────────────────────────────────────────
function Home({hs,onScan,onRc,onCp}){
  if(hs.source==="empty")return(<div style={{display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",minHeight:"80vh",padding:"40px 20px",textAlign:"center"}}><div style={{width:64,height:64,borderRadius:16,background:C.cardH,display:"flex",alignItems:"center",justifyContent:"center",marginBottom:20}}><svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke={C.muted} strokeWidth="1.5"><circle cx="12" cy="12" r="10"/><path d="M12 6v6l4 2"/></svg></div><h2 style={{fontSize:18,fontWeight:700,color:C.text,marginBottom:8}}>아직 시스템 데이터가 없습니다</h2><p style={{fontSize:13,color:C.dim,marginBottom:28,lineHeight:1.6}}>먼저 2분 스캔으로 현재 감정 OS 상태를 확인하세요</p><Btn primary onClick={onScan} style={{maxWidth:280}}>지금 스캔 시작하기</Btn></div>);
  const b=BAND[hs.band],fx=getHotFixes(hs.qpr),top=fx[0];
  return(<div style={{padding:"20px 16px 100px"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:18}}><div><div style={{fontSize:10,letterSpacing:4,color:C.accent,textTransform:"uppercase",fontWeight:700}}>Emotion OS</div><div style={{fontSize:18,fontWeight:700,color:C.text,marginTop:2}}>Kernel Dashboard</div></div>{hs.isRc&&hs.delta!=null&&<DBadge delta={hs.delta}/>}</div>
    <Card accent={`${b.c}30`} style={{background:b.bg}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:6}}><span style={{fontSize:12,color:C.dim}}>시스템 가동성</span><Badge text={b.l} color={b.c}/></div><ANum value={hs.avail} color={b.c} size={28} suffix="%"/><MiniBar pct={hs.avail} color={b.c} h={6}/><p style={{fontSize:12,color:C.dim,marginTop:8,lineHeight:1.5}}>{b.d}</p>{hs.spread&&<div style={{marginTop:8,padding:"8px 12px",borderRadius:8,background:`${C.amber}06`,border:`1px solid ${C.amber}20`}}><span style={{fontSize:11,fontWeight:600,color:C.amber}}>복수 영역 동시 부하 감지</span></div>}{hs.source==="recheck_overlay"&&<p style={{fontSize:10,color:C.muted,marginTop:6}}>가동성은 최근 Re-check 기준입니다</p>}</Card>
    <Card><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:6}}><span style={{fontSize:12,color:C.muted}}>현재 활성 패턴</span>{hs.source==="recheck_overlay"&&<span style={{fontSize:9,color:C.muted}}>Full Scan 기준</span>}</div><div style={{display:"flex",gap:8,alignItems:"center",flexWrap:"wrap"}}><span style={{fontSize:15,fontWeight:700,color:C.accent}}>{QL[hs.pq]}</span><Badge text={hs.leak} color={C.blue}/><Badge text={RL[hs.r1]} color={C.purple}/></div>{hs.mode&&<p style={{fontSize:12,color:C.dim,marginTop:8}}><strong style={{color:C.teal}}>{hs.mode}</strong> — {hs.modeD}</p>}</Card>
    {top&&<Card accent={`${C.teal}30`} style={{background:`${C.teal}05`}}><div style={{fontSize:11,color:C.muted,marginBottom:6}}>Quick Patch</div><div style={{fontSize:15,fontWeight:700,color:C.teal,marginBottom:4}}>{top.label}</div><p style={{fontSize:12,color:C.dim,lineHeight:1.5}}>{top.desc}</p><div style={{marginTop:10}}><Btn primary small style={{maxWidth:200}}>{top.cta}</Btn></div></Card>}
    <div style={{display:"flex",gap:8,marginTop:4}}><Btn small onClick={onRc} style={{flex:1}}>Re-check</Btn><Btn small onClick={onCp} style={{flex:1}}>Couple Sync</Btn></div></div>);
}

// ─── SCAN FLOW ──────────────────────────────────────────
function ScanFlow({onComplete,isRc,rcQs}){const qs=isRc?rcQs:QS;const[idx,setIdx]=useState(0);const[ans,setAns]=useState(Array(qs.length).fill(null));const ref=useRef(null);const q=qs[idx];const pick=v=>{const n=[...ans];n[idx]=v;setAns(n);if(idx<qs.length-1)setTimeout(()=>setIdx(idx+1),180);else setTimeout(()=>onComplete(n,qs),250);};useEffect(()=>{if(ref.current){ref.current.style.opacity="0";ref.current.style.transform="translateY(8px)";requestAnimationFrame(()=>{if(ref.current){ref.current.style.transition="opacity 0.3s,transform 0.3s";ref.current.style.opacity="1";ref.current.style.transform="translateY(0)";}});}},[idx]);
  return(<div style={{minHeight:"100vh",display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",padding:"32px 20px 100px"}}><div style={{maxWidth:460,width:"100%"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:6}}><Badge text={isRc?"Re-check":"Full Scan"} color={C.accent}/><span style={{fontSize:12,color:C.muted}}>{idx+1} / {qs.length}</span></div><div style={{width:"100%",height:3,background:C.border,borderRadius:2,overflow:"hidden",marginBottom:26}}><div style={{width:`${((idx+1)/qs.length)*100}%`,height:"100%",background:C.accent,borderRadius:2,transition:"width 0.4s"}}/></div><div ref={ref}><p style={{fontSize:15,color:C.text,lineHeight:1.75,marginBottom:26,minHeight:54}}>{q.p}</p><div style={{display:"flex",flexDirection:"column",gap:9}}>{SCALE.map(o=>{const sel=ans[idx]===o.v;return(<button key={o.v} onClick={()=>pick(o.v)} style={{display:"flex",alignItems:"center",gap:10,padding:"13px 16px",borderRadius:11,border:`1px solid ${sel?C.accent:C.border}`,background:sel?C.accentD:C.card,color:sel?C.text:C.dim,fontSize:14,fontFamily:FF,cursor:"pointer",textAlign:"left"}}><span style={{width:26,height:26,borderRadius:7,display:"flex",alignItems:"center",justifyContent:"center",fontSize:12,fontWeight:700,color:sel?C.accent:C.muted,background:sel?`${C.accent}20`:C.border,flexShrink:0}}>{o.v}</span>{o.l}</button>);})}</div></div><div style={{display:"flex",justifyContent:"space-between",marginTop:18}}><button onClick={()=>idx>0&&setIdx(idx-1)} disabled={idx===0} style={{padding:"6px 12px",borderRadius:6,border:`1px solid ${C.border}`,background:"transparent",color:idx===0?C.border:C.dim,fontSize:11,cursor:idx===0?"default":"pointer",fontFamily:FF}}>이전</button><span style={{fontSize:10,color:C.muted}}>최근 2주 기준</span></div></div></div>);}

// ─── SCAN TAB ───────────────────────────────────────────
function ScanTab({result,onScan,onRc,onCp}){return(<div style={{padding:"20px 16px 100px"}}><h2 style={{fontSize:18,fontWeight:700,color:C.text,marginBottom:16}}>Scan</h2><Card onClick={onScan} style={{cursor:"pointer"}}><div style={{display:"flex",alignItems:"center",gap:12}}><div style={{width:40,height:40,borderRadius:10,background:C.accentD,display:"flex",alignItems:"center",justifyContent:"center"}}><IS a/></div><div><div style={{fontSize:14,fontWeight:700,color:C.text}}>New Full Scan</div><div style={{fontSize:12,color:C.dim}}>21문항 · 약 2분</div></div></div></Card><Card onClick={result?onRc:null} style={{cursor:result?"pointer":"default",opacity:result?1:0.4}}><div style={{display:"flex",alignItems:"center",gap:12}}><div style={{width:40,height:40,borderRadius:10,background:C.tealD,display:"flex",alignItems:"center",justifyContent:"center"}}><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke={C.teal} strokeWidth="2"><polyline points="23 4 23 10 17 10"/><path d="M20.49 15a9 9 0 11-2.12-9.36L23 10"/></svg></div><div><div style={{fontSize:14,fontWeight:700,color:C.text}}>Re-check</div><div style={{fontSize:12,color:C.dim}}>{result?"3~5문항 · 변화 재확인":"Full Scan을 먼저 진행하세요"}</div></div></div></Card><Card onClick={onCp} style={{cursor:"pointer"}}><div style={{display:"flex",alignItems:"center",gap:12}}><div style={{width:40,height:40,borderRadius:10,background:C.blueD,display:"flex",alignItems:"center",justifyContent:"center"}}><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke={C.blue} strokeWidth="2"><path d="M17 21v-2a4 4 0 00-4-4H5a4 4 0 00-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M23 21v-2a4 4 0 00-3-3.87"/><path d="M16 3.13a4 4 0 010 7.75"/></svg></div><div><div style={{fontSize:14,fontWeight:700,color:C.text}}>Couple Sync</div><div style={{fontSize:12,color:C.dim}}>파트너와 관계 진단 시작</div></div></div></Card></div>);}

// ─── ACTION TAB (enriched) ──────────────────────────────
function ActionTab({result}){
  const fx=getHotFixes(result).slice(0,3);const hi=result&&(result.band==="overload"||result.band==="low");
  if(!result)return(<div style={{padding:"20px 16px 100px"}}><h2 style={{fontSize:18,fontWeight:700,color:C.text,marginBottom:8}}>Action</h2><p style={{fontSize:13,color:C.dim,lineHeight:1.6}}>스캔 결과가 있어야 맞춤형 패치를 추천할 수 있습니다.</p></div>);
  const proto=PROTO_DB.find(p=>p.qMatch.includes(result.pq));
  const prac=PRAC_DB.find(p=>p.qMatch.includes(result.pq))||PRAC_DB.find(p=>p.qMatch.includes(result.sq));
  const extra=PRAC_DB.filter(p=>p!==prac&&(p.qMatch.includes(result.pq)||p.qMatch.includes(result.sq))).slice(0,2);
  return(<div style={{padding:"20px 16px 100px"}}><h2 style={{fontSize:18,fontWeight:700,color:C.text,marginBottom:4}}>Action</h2><p style={{fontSize:12,color:C.dim,marginBottom:18}}>현재 상태에 맞는 개입을 실행하세요</p>
    <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:8}}><span style={{fontSize:11,fontWeight:700,color:C.accent,letterSpacing:2,textTransform:"uppercase"}}>Hot Fix</span><span style={{fontSize:10,color:C.muted}}>자동 추천 {fx.length}개</span></div>
    {fx.map((f,i)=>(<Card key={f.ref} accent={i===0?`${C.accent}30`:undefined} style={i===0?{background:`${C.accent}05`}:{}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:6}}><span style={{fontSize:14,fontWeight:700,color:i===0?C.accent:C.text}}>{f.label}</span>{i===0&&<Badge text="최우선" color={C.accent}/>}</div><p style={{fontSize:12,color:C.dim,lineHeight:1.5,marginBottom:10}}>{f.desc}</p><Btn primary={i===0} small>{f.cta}</Btn></Card>))}
    {!hi&&proto&&<><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginTop:18,marginBottom:8}}><span style={{fontSize:11,fontWeight:700,color:C.blue,letterSpacing:2,textTransform:"uppercase"}}>Protocol</span><span style={{fontSize:10,color:C.muted}}>자동 1개</span></div><Card accent={`${C.blue}20`}><div style={{fontSize:14,fontWeight:700,color:C.text,marginBottom:4}}>{proto.label}</div><p style={{fontSize:12,color:C.dim,lineHeight:1.6}}>{proto.desc}</p></Card></>}
    {!hi&&prac&&<><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginTop:18,marginBottom:8}}><span style={{fontSize:11,fontWeight:700,color:C.teal,letterSpacing:2,textTransform:"uppercase"}}>Practice</span><span style={{fontSize:10,color:C.muted}}>추천 {1+extra.length}개</span></div><Card accent={`${C.teal}20`}><div style={{fontSize:13,fontWeight:600,color:C.text,marginBottom:4}}>{prac.label}</div><p style={{fontSize:12,color:C.dim,lineHeight:1.5}}>{prac.desc}</p></Card>{extra.map(e=>(<Card key={e.ref}><div style={{fontSize:13,fontWeight:600,color:C.text,marginBottom:4}}>{e.label}</div><p style={{fontSize:12,color:C.dim,lineHeight:1.5}}>{e.desc}</p></Card>))}</>}
    <div style={{marginTop:18}}><a href={NL.patch} target="_blank" rel="noopener noreferrer" style={{textDecoration:"none"}}><Card style={{textAlign:"center",cursor:"pointer"}}><span style={{fontSize:13,color:C.dim}}>전체 Patch 라이브러리 →</span></Card></a></div></div>);
}

// ─── LIBRARY TAB ────────────────────────────────────────
function LibTab(){const cc={"핵심 프레임":C.accent,"진단 체계":C.blue,"OS 영역":C.teal,"심화 주제":C.purple,"실전 도구":C.amber};return(<div style={{padding:"20px 16px 100px"}}><h2 style={{fontSize:18,fontWeight:700,color:C.text,marginBottom:4}}>Library</h2><p style={{fontSize:12,color:C.dim,marginBottom:20}}>감정공학 백과사전 · 탭하면 노션 문서로 이동합니다</p>{LCATS.map(cat=>{const items=LIB.filter(i=>i.cat===cat);if(!items.length)return null;return(<div key={cat} style={{marginBottom:22}}><div style={{fontSize:11,fontWeight:700,color:cc[cat]||C.dim,letterSpacing:2,textTransform:"uppercase",marginBottom:8}}>{cat}</div>{items.map(item=>(<a key={item.title} href={item.url} target="_blank" rel="noopener noreferrer" style={{textDecoration:"none",display:"block"}}><Card style={{cursor:"pointer"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><div style={{flex:1}}><div style={{fontSize:14,fontWeight:700,color:C.text,marginBottom:3}}>{item.title}</div><p style={{fontSize:12,color:C.dim,margin:0}}>{item.desc}</p></div><span style={{fontSize:14,color:C.muted,marginLeft:8}}>→</span></div></Card></a>))}</div>);})}</div>);}

// ─── RESULT SCREEN ──────────────────────────────────────
function Result({result,onDone,isRc}){const b=BAND[result.band],hi=result.band==="low"||result.band==="overload";
  return(<div style={{padding:"28px 16px 100px",maxWidth:500,margin:"0 auto"}}><div style={{textAlign:"center",marginBottom:22}}><div style={{fontSize:10,letterSpacing:4,color:C.accent,textTransform:"uppercase",fontWeight:700}}>Emotion OS</div><h1 style={{fontSize:20,fontWeight:800,color:C.text,marginTop:6}}>{isRc?"Re-check 결과":"진단 결과"}</h1><p style={{fontSize:12,color:C.muted,marginTop:4}}>최근 2주 기준 시스템 운영 상태</p>{isRc&&result.delta!=null&&<div style={{marginTop:10}}><DBadge delta={result.delta} big/></div>}</div>
    <Card accent={`${b.c}30`} style={{background:b.bg}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:6}}><span style={{fontSize:12,color:C.dim}}>시스템 가동성</span><Badge text={b.l} color={b.c}/></div><ANum value={result.avail} color={b.c} size={26} suffix="%"/><MiniBar pct={result.avail} color={b.c} h={6}/><p style={{fontSize:12,color:C.dim,marginTop:8,lineHeight:1.5}}>{b.d}</p><p style={{fontSize:11,color:C.muted,marginTop:4,lineHeight:1.5}}>{b.sub}</p>{result.spread&&<div style={{marginTop:8,padding:"8px 12px",borderRadius:8,background:`${C.amber}06`,border:`1px solid ${C.amber}20`}}><span style={{fontSize:11,fontWeight:600,color:C.amber}}>복수 영역 동시 부하 감지</span></div>}</Card>
    <Card><div style={{fontSize:12,color:C.muted,marginBottom:8}}>핵심 패턴</div><p style={{fontSize:14,color:C.text,lineHeight:1.6}}>현재 시스템에는 <strong style={{color:C.accent}}>{QL[result.pq]} 누수 패턴</strong>이 가장 강하게 활성화되어 있습니다.</p><p style={{fontSize:13,color:C.dim,marginTop:4}}>보조: {QL[result.sq]}</p><p style={{fontSize:11,color:C.muted,marginTop:8}}>성격 판정이 아니라, 현재 에너지가 어떤 방식으로 새고 있는지 보여 주는 운영 상태입니다.</p></Card>
    <Accordion title="Q유형 점수 분포" defaultOpen={!hi}>{Object.entries(result.nm).sort((a,b)=>b[1]-a[1]).map(([k,v])=>(<div key={k} style={{marginBottom:6}}><div style={{display:"flex",justifyContent:"space-between",fontSize:11,color:k===result.pq?C.accent:C.dim,marginBottom:2}}><span>{QSH[k]}</span><span>{v}%</span></div><MiniBar pct={v} color={k===result.pq?C.accent:k===result.sq?C.blue:C.borderL} h={4}/></div>))}</Accordion>
    <Card><div style={{fontSize:12,color:C.muted,marginBottom:8}}>병목 진단</div><div style={{display:"flex",gap:6,marginBottom:4,flexWrap:"wrap"}}><Badge text={`누수: ${result.leak}`} color={C.accent}/><Badge text={RL[result.r1]} color={C.purple}/></div><R5Radar pr={result.r1} result={result}/><p style={{fontSize:12,color:C.dim,lineHeight:1.5}}>{LD[result.leak]}</p><p style={{fontSize:12,color:C.dim,lineHeight:1.5,marginTop:4}}>{RD[result.r1]}</p></Card>
    <Card accent={`${C.teal}30`} style={{background:`${C.teal}05`}}><div style={{fontSize:12,color:C.muted,marginBottom:6}}>추천 운영 자세</div><div style={{fontSize:16,fontWeight:700,color:C.teal,marginBottom:4}}>{result.mode}</div><p style={{fontSize:12,color:C.dim,lineHeight:1.5}}>{result.modeD}</p><p style={{fontSize:10,color:C.muted,marginTop:8}}>성격을 바꾸라는 뜻이 아니라, 지금 시스템을 덜 망가지게 운영하기 위한 임시 자세입니다.</p></Card>
    <Card><div style={{fontSize:12,color:C.muted,marginBottom:8}}>연결 Bug / Patch</div><a href={BLinks[result.bug]||NL.bug} target="_blank" rel="noopener noreferrer" style={{textDecoration:"none",display:"block"}}><div style={{padding:"10px 14px",borderRadius:8,background:C.bg,marginBottom:6,fontSize:12,color:C.text,display:"flex",justifyContent:"space-between",alignItems:"center",cursor:"pointer"}}><span><span style={{color:C.accent,fontWeight:600,marginRight:6,fontSize:11}}>{result.bug}</span>{result.bugL}</span><span style={{color:C.muted,fontSize:11}}>→</span></div></a><a href={PLinks[result.patch]||NL.patch} target="_blank" rel="noopener noreferrer" style={{textDecoration:"none",display:"block"}}><div style={{padding:"10px 14px",borderRadius:8,background:C.bg,fontSize:12,color:C.teal,display:"flex",justifyContent:"space-between",alignItems:"center",cursor:"pointer"}}><span>→ {result.patchL}</span><span style={{color:C.muted,fontSize:11}}>→</span></div></a><p style={{fontSize:10,color:C.muted,marginTop:8}}>탭하면 해당 카드의 노션 페이지로 이동합니다</p></Card>
    <Card><p style={{fontSize:12,color:C.dim,lineHeight:1.7}}>{hi?b.act:"반복되는 패턴을 이해하면 다음 과열을 더 빨리 막을 수 있습니다."}</p><p style={{fontSize:11,color:C.muted,marginTop:8}}>이 결과는 의료적 진단이 아니라, 반복되는 감정 누수 패턴을 운영 언어로 읽기 위한 안내입니다.</p><div style={{display:"flex",gap:6,marginTop:12,flexWrap:"wrap"}}><a href={NL.q} target="_blank" rel="noopener noreferrer" style={{textDecoration:"none"}}><Badge text="Q유형 총론" color={C.blue}/></a><a href={NL.r5} target="_blank" rel="noopener noreferrer" style={{textDecoration:"none"}}><Badge text="5R 구조" color={C.purple}/></a>{hi&&<a href={NL.rec} target="_blank" rel="noopener noreferrer" style={{textDecoration:"none"}}><Badge text="리커버리 프로토콜" color={C.teal}/></a>}</div></Card>
    <Btn primary onClick={onDone}>Dashboard로 돌아가기</Btn></div>);}

// ─── LOADING ────────────────────────────────────────────
function Loading({msg}){const[d,setD]=useState("");useEffect(()=>{const iv=setInterval(()=>setD(x=>x.length>=3?"":x+"."),500);return()=>clearInterval(iv);},[]);return(<div style={{minHeight:"100vh",display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",textAlign:"center",padding:40}}><div style={{width:40,height:40,border:`3px solid ${C.border}`,borderTop:`3px solid ${C.accent}`,borderRadius:"50%",animation:"esSpin 1s linear infinite",marginBottom:20}}/><p style={{fontSize:14,color:C.text}}>{msg}{d}</p><p style={{fontSize:11,color:C.muted,marginTop:6}}>성격 판정이 아닌 운영 상태 요약입니다.</p><style>{`@keyframes esSpin{to{transform:rotate(360deg)}} @keyframes dF{from{opacity:0;transform:translateY(4px)}to{opacity:1;transform:translateY(0)}}`}</style></div>);}

// ─── COUPLE BRIDGE ──────────────────────────────────────
function Couple({onBack}){const[code]=useState(()=>{const c="ABCDEFGHJKLMNPQRSTUVWXYZ23456789";let r="";for(let i=0;i<6;i++)r+=c[Math.floor(Math.random()*c.length)];return r;});
  return(<div style={{minHeight:"100vh",display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",padding:"40px 20px",textAlign:"center"}}><div style={{fontSize:10,letterSpacing:4,color:C.blue,textTransform:"uppercase",fontWeight:700,marginBottom:16}}>Couple OS</div><h2 style={{fontSize:20,fontWeight:700,color:C.text,marginBottom:12}}>파트너와 연결하기</h2><p style={{fontSize:13,color:C.dim,lineHeight:1.7,maxWidth:340,marginBottom:28}}>두 사람의 개인 스캔 결과를 연결하면<br/>관계 동기화율, 충돌 패턴, 관계 버퍼를 분석합니다.</p>
    <Card style={{maxWidth:300,width:"100%",textAlign:"center"}}><div style={{fontSize:11,color:C.muted,marginBottom:8}}>파트너 연결 코드</div><div style={{fontSize:32,fontWeight:800,color:C.blue,letterSpacing:8,marginBottom:8}}>{code}</div><p style={{fontSize:12,color:C.dim}}>이 코드를 파트너에게 공유하세요</p></Card>
    <Card style={{maxWidth:300,width:"100%",marginTop:4}}><div style={{fontSize:13,fontWeight:600,color:C.text,marginBottom:6}}>연결 방법</div><div style={{fontSize:12,color:C.dim,lineHeight:1.7}}>1. 두 사람 모두 개인 Full Scan 완료<br/>2. 한 쪽이 코드를 생성하고 공유<br/>3. 파트너가 코드를 입력하면 연결<br/>4. Couple OS 관계 분석 시작</div></Card>
    <p style={{fontSize:11,color:C.muted,marginTop:16,maxWidth:300,lineHeight:1.5}}>상대의 상세 점수는 직접 노출되지 않으며, 관계 상태 요약만 제공됩니다.</p>
    <div style={{marginTop:16,maxWidth:300,width:"100%"}}><Btn small onClick={onBack}>돌아가기</Btn></div></div>);}

// ─── MAIN APP ───────────────────────────────────────────
export default function EmotionOSApp(){
  const[tab,setTab]=useState("home");const[scr,setScr]=useState("tabs");const[fs,setFs]=useState(null);const[lr,setLr]=useState(null);const[rcQs,setRcQs]=useState([]);
  const hs=deriveHS(fs,lr),cr=lr||fs;
  return(<div style={{fontFamily:FF,background:C.bg,color:C.text,minHeight:"100vh",WebkitFontSmoothing:"antialiased"}}><link href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/static/pretendard.min.css" rel="stylesheet"/>
    {scr==="tabs"&&<>{tab==="home"&&<Home hs={hs} onScan={()=>setScr("scan")} onRc={()=>{const b=fs||lr;if(!b)return;setRcQs(getRecheckQs(b));setScr("rc");}} onCp={()=>setScr("cp")}/>}{tab==="scan"&&<ScanTab result={cr} onScan={()=>setScr("scan")} onRc={()=>{const b=fs||lr;if(!b)return;setRcQs(getRecheckQs(b));setScr("rc");}} onCp={()=>setScr("cp")}/>}{tab==="action"&&<ActionTab result={cr}/>}{tab==="library"&&<LibTab/>}<BNav tab={tab} setTab={setTab}/></>}
    {scr==="scan"&&<ScanFlow onComplete={a=>{setScr("ld");setTimeout(()=>{const r=calcFull(a);setFs(r);setLr(r);setScr("res");},1800);}}/>}
    {scr==="rc"&&<ScanFlow onComplete={(a,q)=>{setScr("ld");const b=fs||lr;setTimeout(()=>{setLr(calcRecheck(a,q,b));setScr("rcRes");},1500);}} isRc rcQs={rcQs}/>}
    {scr==="ld"&&<Loading msg="시스템 패턴 분석 중"/>}
    {scr==="res"&&cr&&<Result result={cr} onDone={()=>{setScr("tabs");setTab("home");}}/>}
    {scr==="rcRes"&&cr&&<Result result={cr} onDone={()=>{setScr("tabs");setTab("home");}} isRc/>}
    {scr==="cp"&&<Couple onBack={()=>{setScr("tabs");setTab("home");}}/>}
  </div>);
}